"""Small reusable helpers for the PICID workshop notebook."""

from __future__ import annotations

import logging
import os
from collections import defaultdict
from copy import deepcopy
from dataclasses import dataclass
from functools import partial
from importlib.util import find_spec
from pathlib import Path, PosixPath
from typing import Any

WORKSHOP_ROOT = Path(__file__).resolve().parent
SEED = 7
SEQ_LEN = 24
STRIDE = 4
N_ESTIMATORS = 25
DEEP_LEARNING_EPOCHS = 30


def configure_picid_paths(workshop_root: Path = WORKSHOP_ROOT) -> None:
    """Use PICID's installed configs while keeping outputs in the workshop."""

    picid_spec = find_spec("picid")
    if picid_spec is None or not picid_spec.submodule_search_locations:
        raise RuntimeError("PICID is not installed. Run `uv sync` first.")

    picid_package = Path(next(iter(picid_spec.submodule_search_locations))).resolve()
    local_artifacts = workshop_root / "artifacts"
    local_cache = workshop_root / ".cache" / "picid"
    path_environment = {
        "PROJECT_ROOT": workshop_root,
        "TAB_PHM_ROOT_DIR": workshop_root,
        "TAB_PHM_CONFIG_PATH": picid_package / "configs",
        "TAB_PHM_OUTPUT_DIR": local_artifacts,
        "TAB_PHM_DATA_DIR": workshop_root / "data",
        "TAB_PHM_DATASET_DIR": workshop_root / "data",
        "TAB_PHM_CACHE_PATH": local_cache,
        "TAB_PHM_CACHE_DIR": local_cache,
        "TAB_PHM_LOG_DIR": local_artifacts / "logs",
        "TAB_PHM_PLOT_DIR": local_artifacts / "plots",
        "TAB_PHM_EVAL_DETAILS": local_artifacts / "eval_details",
        "TAB_PHM_MODEL_WORKDIR": local_artifacts / "model_workdir",
        "TAB_PHM_CKPT_DIR": local_artifacts / "checkpoints",
        "TAB_PHM_ARTIFACTS_DIR": local_artifacts,
        "TAB_PHM_MODEL_CACHE_DIR": local_artifacts / "model_cache",
        "TAB_PHM_SAVE_DIR": local_artifacts / "saved",
    }
    for variable, path in path_environment.items():
        os.environ.setdefault(variable, str(path))


# PICID reads its settings during import, so configure its environment first.
configure_picid_paths()

import joblib
import numpy as np
import pandas as pd
import torch
from numpy._core.multiarray import scalar
from omegaconf.base import ContainerMetadata, Metadata
from omegaconf.dictconfig import DictConfig
from omegaconf.nodes import AnyNode
from picid.data.data_objects.validation import (
    build_split_alignment_report_table,
    collect_split_alignment_report,
)
from picid.evaluator.buffer import PredictionBuffer
from picid.evaluator.default import DefaultEvaluator
from picid.evaluator.scaling_wrapper import ScalingWrapper
from picid.loss.default import MSELoss
from picid.metrics.manager import MetricManager
from picid.metrics.metrics import MAEMetric, MSEMetric, RMSEMetric
from picid.model.adapters.base import AbstractFitPredictWrapper
from picid.model.definitions import REGRESSION_TASKS
from picid.model.estimators.mlp.model import MLP
from picid.transforms.base import DataTransform
from picid.transforms.base_transforms.scaler import MinMaxScalerSklearn
from rich.table import Table
from sklearn.linear_model import BayesianRidge
from sklearn.tree import DecisionTreeRegressor

logging.getLogger("picid.interface.interface").setLevel(logging.WARNING)
logging.getLogger("picid.interface.datasources").setLevel(logging.WARNING)
logging.getLogger("picid.data.datasets.hydra_concat_dataset").setLevel(
    logging.WARNING
)


def _allow_picid_checkpoint_globals() -> None:
    """Allow PyTorch 2.6+ to restore checkpoints generated by this local run."""

    torch.serialization.add_safe_globals(
        [
            Any,
            AnyNode,
            ContainerMetadata,
            DefaultEvaluator,
            DictConfig,
            MAEMetric,
            MSELoss,
            MSEMetric,
            Metadata,
            MetricManager,
            PosixPath,
            PredictionBuffer,
            RMSEMetric,
            ScalingWrapper,
            defaultdict,
            dict,
            np.dtype,
            type(np.dtype(np.bool_)),
            type(np.dtype(np.float32)),
            type(np.dtype(np.float64)),
            type(np.dtype(np.int64)),
            partial,
            scalar,
            torch.nn.MSELoss,
            torch.optim.AdamW,
            torch.optim.lr_scheduler.ReduceLROnPlateau,
        ]
    )


_allow_picid_checkpoint_globals()


class FitPredictBayesianRidgeWrapper(AbstractFitPredictWrapper):
    """Run scikit-learn's Bayesian ridge regressor through PICID's adapter API."""

    def __init__(
        self,
        task_type: str,
        *,
        model_cache_path: str | Path | None = None,
        compute_score: bool = True,
        max_iter: int = 300,
        tol: float = 1e-3,
        **kwargs: Any,
    ) -> None:
        if task_type not in REGRESSION_TASKS:
            raise ValueError(
                "FitPredictBayesianRidgeWrapper supports only regression tasks; "
                f"received {task_type!r}."
            )

        self.task_type = task_type
        self.model_cache_path = (
            WORKSHOP_ROOT / "artifacts" / "model_cache" / "bayesian_ridge"
            if model_cache_path is None
            else Path(model_cache_path)
        )
        backbone = BayesianRidge(
            compute_score=compute_score,
            max_iter=max_iter,
            tol=tol,
        )
        super().__init__(backbone=backbone, task_type=task_type, **kwargs)

    def _call_fit(self, X: torch.Tensor, y: torch.Tensor) -> None:
        """Convert PICID tensors to the one-target arrays expected by sklearn."""

        features = X.detach().cpu().numpy().astype(np.float64, copy=False)
        targets = y.detach().cpu().numpy().reshape(-1).astype(np.float64, copy=False)
        if not np.isfinite(features).all() or not np.isfinite(targets).all():
            raise ValueError("Bayesian ridge received non-finite training values.")
        # Accelerate-backed NumPy may emit spurious overflow warnings from dot even
        # when sklearn's fitted coefficients and evidence scores remain finite.
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            self.backbone.fit(features, targets)
        if not np.isfinite(self.backbone.coef_).all():
            raise FloatingPointError("Bayesian ridge fitted non-finite coefficients.")

    def _call_predict(self, X: torch.Tensor) -> torch.Tensor:
        """Return point predictions in PICID's tensor format."""

        features = X.detach().cpu().numpy().astype(np.float64, copy=False)
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            predictions = self.backbone.predict(features)
        if not np.isfinite(predictions).all():
            raise FloatingPointError("Bayesian ridge returned non-finite predictions.")
        predictions = predictions.astype(np.float32, copy=False)
        return torch.from_numpy(predictions)

    def predict_distribution(
        self,
        X: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Expose Bayesian mean and standard deviation for later diagnostics."""

        features = X.detach().cpu().numpy().astype(np.float64, copy=False)
        with np.errstate(divide="ignore", over="ignore", invalid="ignore"):
            mean, standard_deviation = self.backbone.predict(
                features,
                return_std=True,
            )
        if not np.isfinite(mean).all() or not np.isfinite(standard_deviation).all():
            raise FloatingPointError(
                "Bayesian ridge returned a non-finite predictive distribution."
            )
        return (
            torch.from_numpy(mean.astype(np.float32, copy=False)).reshape(-1, 1),
            torch.from_numpy(
                standard_deviation.astype(np.float32, copy=False)
            ).reshape(-1, 1),
        )

    def _model_path(self, task_id: str | int) -> Path:
        if task_id is None:
            raise ValueError("A PICID task id is required for model caching.")
        return self.model_cache_path / f"{task_id}.joblib"

    def serialize_model(self, task_id: str | int) -> str:
        """Persist the fitted estimator for PICID's validation/test reload."""

        model_path = self._model_path(task_id)
        model_path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self.backbone, model_path)
        return str(model_path)

    def load_model(self, task_id: str | int) -> BayesianRidge:
        """Restore the estimator selected by PICID's task id."""

        self.backbone = joblib.load(self._model_path(task_id))
        return self.backbone

    @property
    def allows_multi_target(self) -> bool:
        """BayesianRidge accepts one RUL target at a time."""

        return False


class FitPredictDecisionTreeWrapper(AbstractFitPredictWrapper):
    """Run scikit-learn's decision-tree regressor through PICID's adapter API."""

    def __init__(
        self,
        task_type: str,
        *,
        model_cache_path: str | Path | None = None,
        max_depth: int | None = 6,
        min_samples_leaf: int = 20,
        random_state: int = SEED,
        **kwargs: Any,
    ) -> None:
        if task_type not in REGRESSION_TASKS:
            raise ValueError(
                "FitPredictDecisionTreeWrapper supports only regression tasks; "
                f"received {task_type!r}."
            )

        self.task_type = task_type
        self.model_cache_path = (
            WORKSHOP_ROOT / "artifacts" / "model_cache" / "decision_tree_24_step"
            if model_cache_path is None
            else Path(model_cache_path)
        )
        backbone = DecisionTreeRegressor(
            max_depth=max_depth,
            min_samples_leaf=min_samples_leaf,
            random_state=random_state,
        )
        super().__init__(backbone=backbone, task_type=task_type, **kwargs)

    def _call_fit(self, X: torch.Tensor, y: torch.Tensor) -> None:
        """Convert PICID tensors to the one-target arrays expected by sklearn."""

        features = X.detach().cpu().numpy()
        targets = y.detach().cpu().numpy().reshape(-1)
        if not np.isfinite(features).all() or not np.isfinite(targets).all():
            raise ValueError("Decision tree received non-finite training values.")
        self.backbone.fit(features, targets)

    def _call_predict(self, X: torch.Tensor) -> torch.Tensor:
        """Return decision-tree predictions in PICID's tensor format."""

        features = X.detach().cpu().numpy()
        predictions = self.backbone.predict(features)
        if not np.isfinite(predictions).all():
            raise FloatingPointError("Decision tree returned non-finite predictions.")
        return torch.from_numpy(predictions.astype(np.float32, copy=False))

    def _model_path(self, task_id: str | int) -> Path:
        if task_id is None:
            raise ValueError("A PICID task id is required for model caching.")
        return self.model_cache_path / f"{task_id}.joblib"

    def serialize_model(self, task_id: str | int) -> str:
        """Persist the fitted estimator for PICID's validation/test reload."""

        model_path = self._model_path(task_id)
        model_path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self.backbone, model_path)
        return str(model_path)

    def load_model(self, task_id: str | int) -> DecisionTreeRegressor:
        """Restore the estimator selected by PICID's task id."""

        self.backbone = joblib.load(self._model_path(task_id))
        return self.backbone

    @property
    def allows_multi_target(self) -> bool:
        """DecisionTreeRegressor is kept to one RUL target in this tutorial."""

        return False


@dataclass
class PreparedExperiment:
    """Processed views plus metadata consumed by inspection and plotting helpers."""

    experiment: Any
    unit_frames: dict[str, pd.DataFrame]
    unit_summary: pd.DataFrame
    unit_names: list[str]
    unit_names_by_split: dict[str, list[str]]
    unit_lengths_by_split: dict[str, dict[str, int]]
    split_alignment_report: dict[str, Any]
    deep_learning_processed: Any
    fit_predict_processed: Any
    windowed_fit_predict_processed: Any
    deep_shapes: list[tuple[int, ...]]
    fit_predict_shapes: list[tuple[int, ...]]
    windowed_fit_predict_shapes: list[tuple[int, ...]]
    seq_len: int


@dataclass
class TrainingRun:
    """Returned metrics and artifact locations for one seven-model run."""

    fit_predict_results: list[dict[str, Any]]
    bayesian_fit_predict_results: list[dict[str, Any]]
    windowed_fit_predict_results: list[dict[str, Any]]
    bayesian_windowed_fit_predict_results: list[dict[str, Any]]
    decision_tree_results: list[dict[str, Any]]
    deep_learning_results: list[dict[str, Any]]
    custom_unet_results: list[dict[str, Any]]
    result_frame: pd.DataFrame
    deep_metrics_path: Path
    custom_unet_metrics_path: Path
    mlp_checkpoint_path: Path
    custom_unet_checkpoint_path: Path
    xgboost_model_path: Path
    bayesian_model_path: Path
    windowed_xgboost_model_path: Path
    windowed_bayesian_model_path: Path
    decision_tree_model_path: Path
    trace_version: str
    deep_learning_epochs: int


@dataclass
class CheckpointUnroll:
    """Time-aligned restored-model predictions and baseline diagnostics."""

    windows: pd.DataFrame
    unit_summary: pd.DataFrame
    split_summary: pd.DataFrame
    constant_prediction: float
    mlp_checkpoint_path: Path
    custom_unet_checkpoint_path: Path


def scaling_transforms() -> list[DataTransform]:
    """Return fresh feature and target scalers for one preprocessing view."""

    return [
        DataTransform(
            transform_name="scale_features",
            transform=MinMaxScalerSklearn(),
            metadata={"apply_to": "features", "fit_on": "train"},
        ),
        DataTransform(
            transform_name="scale_rul",
            transform=MinMaxScalerSklearn(),
            metadata={"apply_to": "rul", "fit_on": "train"},
        ),
    ]


def summarize_prepared_experiment(
    *,
    experiment: Any,
    unit_frames: dict[str, pd.DataFrame],
    unit_summary: pd.DataFrame,
    unit_names: list[str],
    unit_names_by_split: dict[str, list[str]],
    deep_learning_processed: Any,
    fit_predict_processed: Any,
    windowed_fit_predict_processed: Any,
    seq_len: int,
) -> PreparedExperiment:
    """Collect shape and split-alignment metadata after notebook preprocessing."""

    data_dict = deep_learning_processed.data_dict
    expected_units = set(unit_names)
    assigned_units = [
        unit_name
        for split in ("train", "val", "test")
        for unit_name in unit_names_by_split[split]
    ]
    if len(assigned_units) != len(set(assigned_units)):
        raise ValueError("Each unit must belong to exactly one split.")
    if set(assigned_units) != expected_units:
        raise ValueError(
            "The by-unit split must assign every unit exactly once; "
            f"expected={sorted(expected_units)}, assigned={sorted(assigned_units)}"
        )

    unit_lengths_by_split = {}
    for split, split_data in data_dict.items():
        split_unit_names = unit_names_by_split[split]
        split_features = split_data["features"]
        if len(split_unit_names) != len(split_features):
            raise ValueError(
                f"PICID returned {len(split_features)} units for {split}, but the "
                f"configured by-unit split contains {len(split_unit_names)} names."
            )
        unit_lengths_by_split[split] = {
            unit_name: len(unit_features)
            for unit_name, unit_features in zip(
                split_unit_names,
                split_features,
                strict=True,
            )
        }
    keys = sorted({key for split_data in data_dict.values() for key in split_data})
    payloads = [
        (key, {split: data_dict[split].get(key, []) for split in data_dict})
        for key in keys
    ]
    split_alignment_report = collect_split_alignment_report(payloads)
    deep_shapes = [unit.shape for unit in data_dict["train"]["features"]]
    fit_predict_shapes = [
        unit.shape
        for unit in fit_predict_processed.data_dict["train"]["features"]
    ]
    windowed_fit_predict_shapes = [
        unit.shape
        for unit in windowed_fit_predict_processed.data_dict["train"]["features"]
    ]
    return PreparedExperiment(
        experiment=experiment,
        unit_frames=unit_frames,
        unit_summary=unit_summary,
        unit_names=unit_names,
        unit_names_by_split=unit_names_by_split,
        unit_lengths_by_split=unit_lengths_by_split,
        split_alignment_report=split_alignment_report,
        deep_learning_processed=deep_learning_processed,
        fit_predict_processed=fit_predict_processed,
        windowed_fit_predict_processed=windowed_fit_predict_processed,
        deep_shapes=deep_shapes,
        fit_predict_shapes=fit_predict_shapes,
        windowed_fit_predict_shapes=windowed_fit_predict_shapes,
        seq_len=seq_len,
    )


def split_alignment_table(prepared: PreparedExperiment) -> Table:
    """Return PICID's Rich table for the prepared split-alignment report."""

    return build_split_alignment_report_table(prepared.split_alignment_report)


def execution_comparison_table() -> Table:
    """Describe the seven model paths used by the tutorial."""

    comparison = Table(title="Seven model paths, two execution styles")
    comparison.add_column("Aspect", style="bold cyan")
    comparison.add_column("XGBoost point")
    comparison.add_column("Bayesian point")
    comparison.add_column("XGBoost 24-step")
    comparison.add_column("Bayesian 24-step")
    comparison.add_column("Decision tree 24-step")
    comparison.add_column("PICID MLP")
    comparison.add_column("Custom U-Net")
    comparison.add_row(
        "Model",
        "xgboost_fit_predict",
        "BayesianRidge",
        "xgboost_fit_predict",
        "BayesianRidge",
        "DecisionTreeRegressor",
        "mlp",
        "SmallUNet1D",
    )
    comparison.add_row(
        "Training API",
        "fit(X, y)",
        "fit(X, y)",
        "fit(X, y)",
        "fit(X, y)",
        "fit(X, y)",
        "minibatches + backpropagation",
        "minibatches + backpropagation",
    )
    comparison.add_row(
        "Input view",
        "current sample (6 values)",
        "current sample (6 values)",
        "24-step history (144 values)",
        "24-step history (144 values)",
        "24-step history (144 values)",
        "sliding windows per unit",
        "sliding windows per unit",
    )
    comparison.add_row(
        "Optimisation",
        "gradient-boosted trees",
        "Bayesian evidence maximisation",
        "gradient-boosted trees",
        "Bayesian evidence maximisation",
        "greedy variance reduction",
        "AdamW over epochs",
        "AdamW over epochs",
    )
    comparison.add_row(
        "Ragged units",
        "concatenated without padding",
        "concatenated without padding",
        "tabularized, then concatenated",
        "tabularized, then concatenated",
        "tabularized, then concatenated",
        "windowed separately",
        "windowed separately",
    )
    return comparison


def make_trace_version(
    *,
    seed: int = SEED,
    deep_learning_epochs: int = DEEP_LEARNING_EPOCHS,
) -> str:
    """Return the deterministic CSV logger version used by all model paths."""

    return f"trace_{deep_learning_epochs}epochs_seed{seed}_cstr_v4_learnable_by_unit"


def _best_checkpoint(checkpoint_dir: Path) -> Path:
    """Resolve the lowest-validation-loss checkpoint in one branch directory."""

    checkpoint_paths = sorted(Path(checkpoint_dir).glob("*.ckpt"))
    if not checkpoint_paths:
        raise FileNotFoundError(f"No checkpoint found in {checkpoint_dir}")

    def validation_loss(path: Path) -> float:
        marker = "val_loss"
        try:
            return float(path.stem.split(marker, maxsplit=1)[1])
        except (IndexError, ValueError):
            return float("inf")

    return min(checkpoint_paths, key=validation_loss)


def _load_backbone_state(model: torch.nn.Module, checkpoint_path: Path) -> None:
    """Load the backbone portion of a PICID Lightning checkpoint in place."""

    checkpoint = torch.load(
        checkpoint_path,
        map_location="cpu",
        weights_only=False,
    )
    prefix = "backbone.backbone."
    backbone_state = {
        key.removeprefix(prefix): value
        for key, value in checkpoint["state_dict"].items()
        if key.startswith(prefix)
    }
    if not backbone_state:
        raise ValueError(
            f"Checkpoint {checkpoint_path} contains no '{prefix}*' tensors."
        )
    model.load_state_dict(backbone_state, strict=True)


def _prediction_summary(
    windows: pd.DataFrame,
    group_keys: list[str],
    constant_prediction: float,
) -> pd.DataFrame:
    """Summarize model dynamics and skill relative to one constant baseline."""

    rows: list[dict[str, Any]] = []
    model_columns = {
        "XGBoost": "xgboost_prediction",
        "Bayesian ridge": "bayesian_prediction",
        "XGBoost (24-step)": "xgboost_24_step_prediction",
        "Bayesian ridge (24-step)": "bayesian_24_step_prediction",
        "Decision tree (24-step)": "decision_tree_24_step_prediction",
        "MLP": "mlp_prediction",
        "custom U-Net": "custom_unet_prediction",
    }
    for group_values, group in windows.groupby(group_keys, sort=False):
        if not isinstance(group_values, tuple):
            group_values = (group_values,)
        group_metadata = dict(zip(group_keys, group_values, strict=True))
        targets = group["target"].to_numpy(dtype=float)
        constant_errors = targets - constant_prediction
        constant_mse = float(np.mean(np.square(constant_errors)))
        constant_mae = float(np.mean(np.abs(constant_errors)))
        target_std = float(np.std(targets))

        for model_name, prediction_column in model_columns.items():
            predictions = group[prediction_column].to_numpy(dtype=float)
            errors = predictions - targets
            prediction_std = float(np.std(predictions))
            correlation = (
                float(np.corrcoef(predictions, targets)[0, 1])
                if prediction_std > 1e-12 and target_std > 1e-12
                else float("nan")
            )
            mse = float(np.mean(np.square(errors)))
            rows.append(
                {
                    **group_metadata,
                    "model": model_name,
                    "n_windows": len(group),
                    "mse": mse,
                    "mae": float(np.mean(np.abs(errors))),
                    "bias": float(np.mean(errors)),
                    "prediction_std": prediction_std,
                    "target_std": target_std,
                    "std_ratio": (
                        prediction_std / target_std if target_std > 0.0 else np.nan
                    ),
                    "correlation": correlation,
                    "constant_mse": constant_mse,
                    "constant_mae": constant_mae,
                    "skill_vs_constant": (
                        1.0 - mse / constant_mse if constant_mse > 0.0 else np.nan
                    ),
                    "beats_constant": mse < constant_mse,
                }
            )
    return pd.DataFrame(rows)


def build_checkpoint_unroll(
    *,
    prepared: PreparedExperiment,
    run: TrainingRun,
    custom_unet_model: torch.nn.Module,
    stride: int,
) -> CheckpointUnroll:
    """Reconstruct aligned predictions from all seven persisted models."""

    input_channels = prepared.deep_shapes[0][-1]
    mlp_model = MLP(
        {
            "seq_len": prepared.seq_len,
            "input_channels": input_channels,
            "hidden_dim": 64,
            "num_layers": 2,
        },
        task_type="regression",
        num_targets=1,
    )
    custom_model = deepcopy(custom_unet_model)
    _load_backbone_state(mlp_model, run.mlp_checkpoint_path)
    _load_backbone_state(custom_model, run.custom_unet_checkpoint_path)
    mlp_model.eval()
    custom_model.eval()
    xgboost_model = joblib.load(run.xgboost_model_path)
    bayesian_model = joblib.load(run.bayesian_model_path)
    windowed_xgboost_model = joblib.load(run.windowed_xgboost_model_path)
    windowed_bayesian_model = joblib.load(run.windowed_bayesian_model_path)
    decision_tree_model = joblib.load(run.decision_tree_model_path)

    window_rows: list[dict[str, Any]] = []
    data_dict = prepared.deep_learning_processed.data_dict
    pointwise_data_dict = prepared.fit_predict_processed.data_dict
    windowed_data_dict = prepared.windowed_fit_predict_processed.data_dict
    with torch.inference_mode():
        for split in ("train", "val", "test"):
            unit_names = prepared.unit_names_by_split[split]
            features_by_unit = data_dict[split]["features"]
            targets_by_unit = data_dict[split]["rul"]
            pointwise_features_by_unit = pointwise_data_dict[split]["features"]
            windowed_features_by_unit = windowed_data_dict[split]["features"]
            windowed_targets_by_unit = windowed_data_dict[split]["rul"]
            for (
                unit_name,
                features,
                targets,
                pointwise_features,
                windowed_features,
                windowed_targets,
            ) in zip(
                unit_names,
                features_by_unit,
                targets_by_unit,
                pointwise_features_by_unit,
                windowed_features_by_unit,
                windowed_targets_by_unit,
                strict=True,
            ):
                start_indices = np.arange(
                    0,
                    len(features) - prepared.seq_len + 1,
                    stride,
                )
                feature_windows = np.stack(
                    [
                        features[start : start + prepared.seq_len]
                        for start in start_indices
                    ]
                )
                target_values = np.asarray(targets)[
                    start_indices + prepared.seq_len - 1,
                    0,
                ]
                end_indices = start_indices + prepared.seq_len - 1
                pointwise_features = np.asarray(pointwise_features).squeeze(0)
                windowed_features = np.asarray(windowed_features).squeeze(0)
                windowed_targets = np.asarray(windowed_targets).squeeze(0)[:, 0]
                if len(windowed_features) != len(end_indices):
                    raise ValueError(
                        "PICID's tabularized history is not aligned with the "
                        f"neural windows for {split}/{unit_name}: "
                        f"{len(windowed_features)} != {len(end_indices)}."
                    )
                if not np.allclose(windowed_targets, target_values):
                    raise ValueError(
                        "PICID's tabularized present targets do not match the "
                        f"neural window endpoints for {split}/{unit_name}."
                    )
                xgboost_predictions = xgboost_model.predict(
                    pointwise_features[end_indices]
                ).astype(np.float32, copy=False)
                bayesian_predictions = bayesian_model.predict(
                    pointwise_features[end_indices]
                ).astype(np.float32, copy=False)
                windowed_xgboost_predictions = windowed_xgboost_model.predict(
                    windowed_features
                ).astype(np.float32, copy=False)
                windowed_bayesian_predictions = windowed_bayesian_model.predict(
                    windowed_features
                ).astype(np.float32, copy=False)
                decision_tree_predictions = decision_tree_model.predict(
                    windowed_features
                ).astype(np.float32, copy=False)
                feature_tensor = torch.as_tensor(
                    feature_windows,
                    dtype=torch.float32,
                )
                mlp_predictions = (
                    mlp_model(feature_tensor.transpose(1, 2))
                    .squeeze(-1)
                    .cpu()
                    .numpy()
                )
                custom_predictions = (
                    custom_model(feature_tensor).squeeze(-1).cpu().numpy()
                )
                for (
                    index,
                    target,
                    xgboost_prediction,
                    bayesian_prediction,
                    windowed_xgboost_prediction,
                    windowed_bayesian_prediction,
                    decision_tree_prediction,
                    mlp_prediction,
                    custom_prediction,
                ) in zip(
                    end_indices,
                    target_values,
                    xgboost_predictions,
                    bayesian_predictions,
                    windowed_xgboost_predictions,
                    windowed_bayesian_predictions,
                    decision_tree_predictions,
                    mlp_predictions,
                    custom_predictions,
                    strict=True,
                ):
                    window_rows.append(
                        {
                            "split": split,
                            "unit": unit_name,
                            "time_index": int(index),
                            "target": float(target),
                            "xgboost_prediction": float(xgboost_prediction),
                            "bayesian_prediction": float(bayesian_prediction),
                            "xgboost_24_step_prediction": float(
                                windowed_xgboost_prediction
                            ),
                            "bayesian_24_step_prediction": float(
                                windowed_bayesian_prediction
                            ),
                            "decision_tree_24_step_prediction": float(
                                decision_tree_prediction
                            ),
                            "mlp_prediction": float(mlp_prediction),
                            "custom_unet_prediction": float(custom_prediction),
                        }
                    )

    windows = pd.DataFrame(window_rows)
    constant_prediction = float(
        windows.loc[windows["split"] == "train", "target"].mean()
    )
    windows["constant_prediction"] = constant_prediction
    unit_summary = _prediction_summary(
        windows,
        ["split", "unit"],
        constant_prediction,
    )
    split_summary = _prediction_summary(
        windows,
        ["split"],
        constant_prediction,
    )
    return CheckpointUnroll(
        windows=windows,
        unit_summary=unit_summary,
        split_summary=split_summary,
        constant_prediction=constant_prediction,
        mlp_checkpoint_path=run.mlp_checkpoint_path,
        custom_unet_checkpoint_path=run.custom_unet_checkpoint_path,
    )


def package_training_run(
    *,
    fit_predict_results: list[dict[str, Any]],
    bayesian_fit_predict_results: list[dict[str, Any]],
    windowed_fit_predict_results: list[dict[str, Any]],
    bayesian_windowed_fit_predict_results: list[dict[str, Any]],
    decision_tree_results: list[dict[str, Any]],
    deep_learning_results: list[dict[str, Any]],
    custom_unet_results: list[dict[str, Any]],
    seed: int = SEED,
    deep_learning_epochs: int = DEEP_LEARNING_EPOCHS,
) -> TrainingRun:
    """Combine returned results and resolve both neural-model metric files."""

    result_rows = []
    for model_family, model_name, results in [
        ("XGBoost", "xgboost_fit_predict", fit_predict_results),
        (
            "Bayesian ridge",
            "bayesian_ridge",
            bayesian_fit_predict_results,
        ),
        (
            "XGBoost (24-step)",
            "xgboost_fit_predict_24_step",
            windowed_fit_predict_results,
        ),
        (
            "Bayesian ridge (24-step)",
            "bayesian_ridge_24_step",
            bayesian_windowed_fit_predict_results,
        ),
        (
            "Decision tree (24-step)",
            "decision_tree_24_step",
            decision_tree_results,
        ),
        ("MLP", "mlp", deep_learning_results),
        ("custom U-Net", "small_unet_1d", custom_unet_results),
    ]:
        metrics = results[0] if results else {}
        result_rows.append(
            {
                "family": model_family,
                "model": model_name,
                **metrics,
            }
        )

    trace_version = make_trace_version(
        seed=seed,
        deep_learning_epochs=deep_learning_epochs,
    )
    deep_metrics_path = (
        WORKSHOP_ROOT
        / "artifacts"
        / "saved"
        / "picid_experiment_deep_learning"
        / trace_version
        / "metrics.csv"
    )
    custom_unet_metrics_path = (
        WORKSHOP_ROOT
        / "artifacts"
        / "saved"
        / "picid_experiment_custom_unet"
        / trace_version
        / "metrics.csv"
    )
    for metrics_path in (deep_metrics_path, custom_unet_metrics_path):
        if not metrics_path.exists():
            raise FileNotFoundError(f"Expected CSV logger output at {metrics_path}")

    checkpoint_root = WORKSHOP_ROOT / "artifacts" / "checkpoints" / trace_version
    mlp_checkpoint_path = _best_checkpoint(checkpoint_root / "mlp")
    custom_unet_checkpoint_path = _best_checkpoint(checkpoint_root / "custom_unet")
    model_cache_root = WORKSHOP_ROOT / "artifacts" / "model_cache"
    xgboost_model_path = model_cache_root / "xgboost" / "0.joblib"
    bayesian_model_path = model_cache_root / "bayesian_ridge" / "0.joblib"
    windowed_xgboost_model_path = (
        model_cache_root / "xgboost_24_step" / "0.joblib"
    )
    windowed_bayesian_model_path = (
        model_cache_root / "bayesian_ridge_24_step" / "0.joblib"
    )
    decision_tree_model_path = (
        model_cache_root / "decision_tree_24_step" / "0.joblib"
    )
    for model_path in (
        xgboost_model_path,
        bayesian_model_path,
        windowed_xgboost_model_path,
        windowed_bayesian_model_path,
        decision_tree_model_path,
    ):
        if not model_path.exists():
            raise FileNotFoundError(f"Expected fit/predict model at {model_path}")

    return TrainingRun(
        fit_predict_results=fit_predict_results,
        bayesian_fit_predict_results=bayesian_fit_predict_results,
        windowed_fit_predict_results=windowed_fit_predict_results,
        bayesian_windowed_fit_predict_results=(
            bayesian_windowed_fit_predict_results
        ),
        decision_tree_results=decision_tree_results,
        deep_learning_results=deep_learning_results,
        custom_unet_results=custom_unet_results,
        result_frame=pd.DataFrame(result_rows),
        deep_metrics_path=deep_metrics_path,
        custom_unet_metrics_path=custom_unet_metrics_path,
        mlp_checkpoint_path=mlp_checkpoint_path,
        custom_unet_checkpoint_path=custom_unet_checkpoint_path,
        xgboost_model_path=xgboost_model_path,
        bayesian_model_path=bayesian_model_path,
        windowed_xgboost_model_path=windowed_xgboost_model_path,
        windowed_bayesian_model_path=windowed_bayesian_model_path,
        decision_tree_model_path=decision_tree_model_path,
        trace_version=trace_version,
        deep_learning_epochs=deep_learning_epochs,
    )
